### ISSUE TITLE
FR: Whitelist sites/products

### ISSUE THREAD

**Issue by skela** [fondberg/easee_hass#160] opened 2022-01-24 19:16 UTC
I have access to a few products, not all of which are at my home (only have 3 at home). 
Would be nice if there was a way to whitelist so that only those 3 or alternatively, whitelist by Site, so that only 1 particular site shows up in Home assistant.
![2022-01-24_20-10](https://user-images.githubusercontent.com/58268/150848752-146a0427-8235-4c81-b0e3-ece22e75f13c.png)

Yes, I know I can disable them in home assistant so they dont show up / aren't used, but for a second I thought i was disabling them in Easee Cloud (via home assistant) (needless to say that scared me a bit. 🤣 ).

Really love what you've done though, amazing work!

**Comment by olalid** [comment] 2022-01-24 19:41
Just press the configure button (as shown in your picture) you should get an interface where you can select which site(s) to monitor.
If you uncheck the sites you do not want, the corresponding chargers/equalizer sensors will be removed, and the subscription for updates from the cloud will be removed.

**Comment by skela** [comment] 2022-01-25 07:32
Awesome, just a tad confusing that its still showing 31 devices, even when I have selected that 1 site.

**Comment by olalid** [comment] 2022-01-25 08:46
Yes, all devices are listed, but the sensors (should) not be available for more than your 3 devices, right?
But agree that this is confusing, we should look in to if that can be changed.

**Comment by olalid** [comment] 2022-01-25 08:49
649 entities seems excessive for your 3 products though...
Something seems fishy here...
Can you send me a private message with screenshots of your configuration page, the devices and the entities?

**Comment by olalid** [comment] 2022-01-25 08:51
You can reach me at olal@plea.se (will remove this when you have replied).

**Comment by skela** [comment] 2022-01-25 09:54
Sure will send it to you. I don't recall seeing the site selector stuff when I went through the wizard to add the Easee integration.
After I added my details, all 31 devices showed up , and i went through the list and "disabled" all of the ones i didnt need.

**Comment by astrandb** [comment] 2022-01-25 10:08
There is something wrong with the removal of devices and entities. They are still there, but unavailable, when i unclick a site on my dev system. Can look into it tomorrow or day after.

**Comment by astrandb** [comment] 2022-01-25 17:25
@skela The problem with the non-deleted devices and entities is a regression. It works as intended in my old production system but I can verify the problem on a fresh install in my dev environment.
I agree that the options flow should be visited automatically at first time install -  if you have more than one site in your account. We will put the FR on the todo list.

**Comment by astrandb** [comment] 2022-01-25 19:22
@skela I cannot reproduce the problem now :-(
There might be a problem with old crap in the config entry registry in HA. Please try to enable all sites in HA, submit and then disable one site and see if it is removed properly.

**Comment by skela** [comment] 2022-01-25 19:24
@astrandb ill give it a go asap, just wondering, do i need to restart HASS in between changes to the easee-hass config, i.e. do i need to restart hass after i select a site and hit Update ?

**Comment by astrandb** [comment] 2022-01-25 19:25
No, it should work withot restart

**Comment by skela** [comment] 2022-01-25 20:15
@astrandb yes, that fixed it!

I hit Configure, selected all of my sites (9 sites), clicked Submit.
Waited 30 seconds just in case there's any kind of download or process that happens when you do that ( i dont know enough about how you've done things).
Refreshed the page.
Clicked Configure, then selected the 1 site I want, clicked Submit.
Devices count shows 3, and entities shows 57, just the way I expected it to.

**Comment by astrandb** [comment] 2022-01-25 20:35
Great!
My headache remains, though. Now your config entry registry is clean and I cannot troubleshoot the root cause.

**Comment by skela** [comment] 2022-01-25 22:46
@astrandb ah , sorry about that. :'D i suppose by making the site selection a part of the intial config flow, maybe the issue will go away completely for 99% of users? Or is the issue due to a bump in different hass-easee version / or hass versions..

**Comment by astrandb** [comment] 2022-01-25 23:02
No, it is a bug in our code. Will be fixed in next release. The extended config flow will need some thoughts so it may come later.

**Closed** 2022-01-27 07:28 UTC
Labels: bug, enhancement
