### ISSUE TITLE
Incorrect sensor state class

### ISSUE THREAD

**Issue by kristianolofsson** [fondberg/easee_hass#141] opened 2021-09-14 11:42 UTC
The sensor state class "measurement" is getting depreciated and replaced with "total_increasing"

https://developers.home-assistant.io/blog/2021/08/16/state_class_total/?fbclid=IwAR2jZqRsgMIYHAwdXCnQFoktmWK__K2gub0OFhc1LiIMtndYQjO6m2QCpow

**Comment by astrandb** [comment] 2021-09-14 11:51
We are aware, and it will be fixed in an upcoming release.
Duplicate of #138

**Closed** 2021-10-03 18:24 UTC
Labels: duplicate
