### ISSUE TITLE
Lifetime energy registered 1 hour delayed

### ISSUE THREAD

**Issue by martin9000andersen** [fondberg/easee_hass#174] opened 2022-03-01 19:40 UTC
### The problem

The "Lifetime energy" is shown in the HA Energy section 1 hour late.
E.g. when charging from 10:01 to 10:59, nothing is shown in the hour 10-11, everything is shown in 11-12.
I can see that "Lifetime energy" is always updated 2-10min passed the hour.
From the documentation this is by design from Easee:
    https://developer.easee.cloud/docs/energy-consumption#lifetime-energy
"The lifetime energy is updated via the API once per hour, approximately on the full hour."
Example response:
{
    "measurements": [
        {
            "value": 4.612513333333333,
            "measuredAt": "2021-12-07T11:00:00+00:00"
        },
        {
            "value": 4.612513333333333,
            "measuredAt": "2021-12-07T12:00:00+00:00"
        }
    ]
}

Would it be possible to save the value to HA, with time forced to 1 sec before "measuredAt"?

If you could fix this, then https://github.com/fondberg/easee_hass/issues/139 might also be fixed, as late response from Easee API will still be registered at the correct measurement time.

(In addition to the graph being of by one, this issue also cause the "Energy cost calculation" to use the wrong kWh-price for people with energy prices that changes over the day)

### Version of Easee integration having the issue?

v0.9.40

### Version of Home Assistant Core having the issue?

Home Assistant 2022.2.9

**Comment by olalid** [comment] 2022-03-01 21:28
Your observations are interesting.
If I look at the measurement logs using the https://developer.easee.cloud/docs/energy-consumption#lifetime-energy I can see that the measurements are indeed logged exactly on the hour as in the example.
But in HA the same update actually occurs between like 5 and 15 minutes after the hour.

But while this is an explanation why things behave a bit strange, it does not really help us since there is no way we can change neither when we receive the new measurement value, nor when HA logs that the change occurred.
This integration does in fact not use the API you are referring to, but instead uses the "signalr" streaming data.
Which means we have really no control over *when* we receive data and we do not have access to that "measuredAt" property. For HA the only important thing is when the senor actually changed value, there is to my knowledge no way we can force HA to believe that a new sensor value was in fact updated some time earlier than when we actually updated it.. Short of editing the history log possibly, but that is not something you are supposed to do.
I am a bit surprised by the long delay though, typically it takes 1-3 seconds for other states to update when they change.
But perhaps it is because all the chargers basically do these measurements at the same time, so it needs to be sent out in a queue to not completely overwhelm the servers.

We could of course try to shorten the measurement interval setting, it would probably provide better, but not perfect results.

**Comment by martin9000andersen** [comment] 2022-03-02 19:57
Thank you very much for your feedback.
Here a charging example
![HA_Easee_charging_graphs](https://user-images.githubusercontent.com/2692211/156433428-c6c80336-e8fc-427e-b9d6-f4c3b3442450.png)
The graph for "Easee Power" is ramping up in 3 sample points: 13:18:05, 13:18:12, and 13:18:17, and ramping down in 2 samples 14:58:07 and 14:58:12. I do not know about the latency, but this graph looks very good. The same is the case for "Easee Session energy" that ends 14:58:07 at 18.4 kWh. If all the Easee data was like this, every thing was perfect.
However "Easee Lifetime energy" and "Easee Energy per hour" are updated exactly once per hour (at same time stamp: 14:04:11 and 15:02:01) and always some minutes after the hour.
"Easee Lifetime energy" starts at 262.3 and ends at 280.7 kWh 15:02:01.

Unfortunately I think that the "signalr" interface access the exact same data as described in https://developer.easee.cloud/docs/energy-consumption#lifetime-energy and "shorten the measurement interval setting" will most likely not change anything for lifetime energy.

**Comment by olalid** [comment] 2022-03-02 20:20
Yes, as I said above, this is the way the data is delivered from the cloud, there is nothing we can do about that.
I have asked Easee for a comment on if this is intended behaviour or not, but I suspect it probably is.

If you enable debug logs for custom_components.easee you can see when the signalr data is received, example:
```
2022-02-28 22:03:36 DEBUG (MainThread) [custom_components.easee.controller] Callback EHXXXXX 124 state_lifetimeEnergy 7794.746040277779
2022-02-28 23:00:47 DEBUG (MainThread) [custom_components.easee.controller] Callback EHXXXXX 124 state_lifetimeEnergy 7800.325811111111
2022-03-01 00:00:47 DEBUG (MainThread) [custom_components.easee.controller] Callback EHXXXXX 124 state_lifetimeEnergy 7806.143643055555
2022-03-01 01:06:49 DEBUG (MainThread) [custom_components.easee.controller] Callback EHXXXXX 124 state_lifetimeEnergy 7811.970360833333
2022-03-01 02:14:16 DEBUG (MainThread) [custom_components.easee.controller] Callback EHXXXXX 124 state_lifetimeEnergy 7817.851658055556
```

**Comment by olalid** [comment] 2022-03-04 15:42
So feedback is that there is random delay added in each charger so that not all chargers try to send the new value to the cloud at the same time.

**Comment by olalid** [comment] 2022-03-04 21:39
I will close this issue since I see no way to do anything about it.

**Closed by olalid** 2022-03-04 21:39 UTC
Labels: bug
