### ISSUE TITLE
Setting up the integration failed (error occurred)

### ISSUE THREAD

**Issue by irqnet** [fondberg/easee_hass#263] opened 2022-12-22 07:49 UTC
### The problem

I've had an issue with my account at eease cloud where login wasn't possible, but it's fixed now and cloud and app is working again.

Setting up the integration again failed with an unknown error. 

### Version of Easee integration having the issue?

0.9.48

### Version of Home Assistant Core having the issue?

2022.12. 8

### Anything in the logs that might be useful for us?

```txt
Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: aiohttp.server
Source: custom_components/easee/config_flow.py:60
Integration: Easee EV Charger (documentation, issues)
First occurred: 08:42:15 (1 occurrences)
Last logged: 08:42:15

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 222, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 81, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 136, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 180, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 73, in wrapper
    result = await method(view, request, data, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 110, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 281, in async_configure
    result = await self._async_handle_step(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 368, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/easee/config_flow.py", line 60, in async_step_user
    await easee.connect()
  File "/usr/local/lib/python3.10/site-packages/pyeasee/easee.py", line 191, in connect
    await raise_for_status(response)
  File "/usr/local/lib/python3.10/site-packages/pyeasee/easee.py", line 61, in raise_for_status
    raise NotFoundException(data)
pyeasee.exceptions.NotFoundException: None
```

**Comment by olalid** [comment] 2022-12-25 12:41
Did you get to enter the username and password again when you tried to add the integration again?
Kind of looks like it failed to login, so just thinking that it might have tried to use the old username/password combination?

**Comment by MarcoPolet** [comment] 2022-12-28 20:14
Hi, I think I have the same problem. Using the same versions as above mentioned.
In the integration overview it says: Retrying setup: 'NoneType' object is not iterable
In the debug log:
2022-12-28 21:00:47.617 INFO (MainThread) [pyeasee.easee] Easee python library version: 0.7.50
2022-12-28 21:00:47.617 DEBUG (MainThread) [pyeasee.easee] getting token for user: XXXX
2022-12-28 21:00:47.765 DEBUG (MainThread) [pyeasee.easee] TOKEN: {'accessToken': 
2022-12-28 21:00:47.765 DEBUG (MainThread) [pyeasee.easee] GET: /api/accounts/products ({})
2022-12-28 21:00:47.765 DEBUG (MainThread) [pyeasee.easee] verify_updated_token: 
2022-12-29 20:59:47.765629, 2022-12-28 21:00:47.765707, False
2022-12-28 21:00:47.814 DEBUG (MainThread) [pyeasee.easee] 
2022-12-28 21:00:47.814 DEBUG (MainThread) [pyeasee.easee] GET: /api/sites/539650?detailed=true ({})
2022-12-28 21:00:47.814 DEBUG (MainThread) [pyeasee.easee] verify_updated_token: 
2022-12-28 21:00:47.885 DEBUG (MainThread) [pyeasee.easee] Site:  ------------------ deleted site info, but seems correct
2022-12-28 21:00:47.885 DEBUG (MainThread) [custom_components.easee.controller] Found site (monitored): 539650 Jokweg
2022-12-28 21:00:47.885 DEBUG (MainThread) [custom_components.easee.controller] Found equalizer: QPWGBWYY QPWGBWYY
2022-12-28 21:00:47.885 DEBUG (MainThread) [custom_components.easee.controller] Found circuit: 511130 Schuur
**_2022-12-28 21:00:47.885 DEBUG (MainThread) [custom_components.easee.controller] Easee server failure 'NoneType' object is not iterable_**
2022-12-28 21:00:47.886 DEBUG (MainThread) [custom_components.easee.controller] Controller deleted
2022-12-28 21:01:27.887 DEBUG (MainThread) [custom_components.easee] Setting up Easee component version 0.9.48

If I use pyeasee from the command line, it finds chargers just fine.

Hope above helps in finding a solution, the integration previously worked fine!
Regards,
Marco

**Comment by olalid** [comment] 2022-12-29 00:21
@MarcoPolet, that actually seems to me like a different problem than what @irqnet was describing above. Your problem is clearly not a login problem since you are in fact retrieving part of the information about your site(s).
I have seen your type of failure happening before and it was a server side problem at that time. When that happened we added that error message, "Easee server failure" as you can see in your log and improved the handling of the error (i.e. made sure it retires instead of just failing).
This type of problem usually clears itself up when the servers are responding normally again, so let us know if you still have the problem.

When you used the command line to test, did you use the -c option? That uses a different API to retrieve the charges information. If you try the -an option it should be more close to what the HA integration uses.

**Comment by irqnet** [comment] 2022-12-29 07:11
It seems that it's not related to an issue of the integration itself but to the Easee API.

Several users of EVCC are facing issues where Easee is blocking the API communication based on the public IPv4, where users with providers using CG-NAT v4 pools are seen as one user on the Easee server side. 

https://feedback.easee.com/b/ideas/more-intelligent-rate-limiting-ipv6-support

A request has been raised to specify the rate limit and to extend the communication to v6.

Furthermore a request for a local API is already open for months.

**Comment by olalid** [comment] 2022-12-29 13:31
What is EVCC?

Rate limiting is not a new thing, this has been the case since forever with the Easee API. It is not really documented and as with everything else on Easee API it can change at any time without previous warning.
The HA integration does in any case not call the API until it is absolutely necessary. All status updates are pushed over a signalr stream at the servers discretion, so there is no polling. And if the user manipulates a setting (e.g. by calling a service) the API is only called if the setting is new (i.e. repeatedly calling a service with the same value will only call the API the first time).
So we are doing what we can to limit the amount of calls we make to the API. If there is a large amount of users with the same IP, it might not be enough though. I would think the rate limit is implemented on user level rather than IP level though...?

If EVCC (whatever that is) is also manipulating the API directly, it probably needs to implement similar things to make sure it does not trigger the rate limits.

The request for a local API has been active since several years.

**Comment by MarcoPolet** [comment] 2022-12-29 16:03
@olalid Thanks for your feedback! Just tried the -a switch from the commandline, this works fine (finds my site, circuit, equalizer  and charger). Hope it will be fixed soon on easee side!

**Comment by olalid** [comment] 2022-12-29 19:39
@MarcoPolet if you want to you can share the output of the -a command to my email olal (a) plea.se
There could be some other problem if the problem is still persisting for you.

**Comment by MarcoPolet** [comment] 2022-12-29 19:52
Thanks Olal! Sent you a pm!

**Comment by irqnet** [comment] 2022-12-30 10:39
> What is EVCC?
> 
> Rate limiting is not a new thing, this has been the case since forever with the Easee API. It is not really documented and as with everything else on Easee API it can change at any time without previous warning.
> The HA integration does in any case not call the API until it is absolutely necessary. All status updates are pushed over a signalr stream at the servers discretion, so there is no polling. And if the user manipulates a setting (e.g. by calling a service) the API is only called if the setting is new (i.e. repeatedly calling a service with the same value will only call the API the first time).
> So we are doing what we can to limit the amount of calls we make to the API. If there is a large amount of users with the same IP, it might not be enough though. I would think the rate limit is implemented on user level rather than IP level though...?
> The IP filtering is more like a BAN because of previous misbehaving calls to the API I would guess?
> 
> If EVCC (whatever that is) is also manipulating the API directly, it probably needs to implement similar things to make sure it does not trigger the rate limits.
> 
> The request for a local API has been active since several years.

EVCC is an charge controller software, which communicates with the PV, Wallbox and vehicle to adapt the charge settings based on PV production level (excess) to use PV energy whenever possible to charge your vehicle.

Not sure how the API implementation to easee is coded in evcc.

**Comment by MarcoPolet** [comment] 2022-12-31 19:32
Thanks to Ola's support it is now solved! It is really strange, indeed pyeasee is working fine, also on the easee.cloud I see all data, equalizer & charger. BUT! If I open the Easee app (Android), I only saw the Equalizer. I could add the charger by it's serial number & pincode, after that, the component in HA worked too!! Very strange that there appear to be two kind of api's or something, but I'm glad it is solved!

**Comment by olalid** [comment] 2022-12-31 21:34
That is good. I suspect that your chargers ownership was not correctly recorded in the easee databases for some reason.

**Comment by olalid** [comment] 2023-01-02 21:21
@irqnet not sure how to proceed with your issue.
If it really is a rate limit problem within EVCC there is not much I can do, perhaps short of providing some advice to the developers of EVCC perhaps, but...
As I said above, I am pretty sure that we are already doing what we can to not cause rate limiting issues.

**Comment by irqnet** [comment] 2023-01-02 21:24
> @irqnet not sure how to proceed with your issue.
> If it really is a rate limit problem within EVCC there is not much I can do, perhaps short of providing some advice to the developers of EVCC perhaps, but...
> As I said above, I am pretty sure that we are already doing what we can to not cause rate limiting issues.

No worries, issue is already addressed on the EVCC project.

As the integration is working again, the issue could be closed.

But we should keep in mind that other software running in parallel may interfere with your integration, when the rate limit exceeds on the Easee side.

**Closed** 2023-01-04 12:24 UTC
Labels: bug, more info requested
