### ISSUE TITLE
Equalizer export energy not updating even though export power is there

### ISSUE THREAD

**Issue by wanders** [fondberg/easee_hass#204] opened 2022-08-24 13:00 UTC
### The problem

Since around 2022-08-20 "export energy" is not increasing. But momentanous "export power" is there.

This seems to be happening since after the easee outage.

Energy:
![image](https://user-images.githubusercontent.com/1566016/186423692-980d7ce5-2f85-43b8-9beb-31291cb3672c.png)

Power:
![image](https://user-images.githubusercontent.com/1566016/186423851-d3788aaa-c395-469b-907e-d72eec5696a4.png)

Possibly same issue as #203

Have not tried debugging further, wether it is stale data from cloud or integration failing to update.

### Version of Easee integration having the issue?

v0.9.43

### Version of Home Assistant Core having the issue?

2022.6.6

**Comment by olalid** [comment] 2022-08-24 13:35
Yes, I have noticed this too. 
The problem is on the server side, so we can not really do anthing but report to Easee.
Feel free to contact them too if you want.

**Comment by olalid** [comment] 2022-09-07 06:20
It seems the cloud is now sending the export energy information again, for you as well @wanders ?

**Comment by wanders** [comment] 2022-09-07 12:15
Yes, I'm getting data now.

**Comment by olalid** [comment] 2022-09-07 18:56
Resolved on server side. Closing.

**Closed by olalid** 2022-09-07 18:56 UTC
Labels: bug
