### ISSUE TITLE
State class is missing

### ISSUE THREAD

**Issue by rhoddan** [fondberg/easee_hass#138] opened 2021-09-01 21:30 UTC
![IMG_0110](https://user-images.githubusercontent.com/33499995/131747722-748590df-3f6c-43fd-8cc1-55ab677052bc.jpeg)

unexpected state class error with 2021.09.0

**Comment by astrandb** [comment] 2021-09-01 21:45
This is a warning message that this integration is not fully compatible with v 2021.09. It should work as intended anyway. 
Will be fixed...

**Comment by gulli1986** [comment] 2021-09-10 07:52
After update to core-2021.9.5, looks like the following showed up. I guess it is also related to the above:

`2021-09-10 09:50:44 WARNING (MainThread) [homeassistant.components.sensor] Entity sensor.easee_equalizer_home_import_energy_cost (<class 'homeassistant.components.energy.sensor.EnergyCostSensor'>) with state_class measurement has set last_reset. Setting last_reset is deprecated and will be unsupported from Home Assistant Core 2021.11. Please update your configuration if state_class is manually configured, otherwise create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+energy%22`

**Closed** 2021-10-03 18:24 UTC
