### ISSUE TITLE
Error messages in log

### ISSUE THREAD

**Issue by rhoddan** [fondberg/easee_hass#140] opened 2021-09-12 21:00 UTC
Any ideas why I get these errors?

![IMG_0115](https://user-images.githubusercontent.com/33499995/133002609-6fa7d1c4-852d-409f-8465-5666ee0ecb2e.jpeg)

![IMG_0117](https://user-images.githubusercontent.com/33499995/133002611-f161fcea-dd22-43a1-86d4-ef98f8ebed0f.jpeg)

**Comment by olalid** [comment] 2021-09-27 14:49
The root cause of this is that the server has some issue and responds with an error code which is not handled very well in the pyeasee lib.
We are working on a fix, but it might take a while before we are confident it works since this is hard to reproduce on demand.
See this PR: https://github.com/fondberg/pyeasee/pull/57

**Comment by olalid** [comment] 2022-06-02 20:19
Closing this because I believe it is solved, at least to 99%...

**Closed by olalid** 2022-06-02 20:19 UTC
